[workspace]
resolver = "2"

[package]
name = "hls_bot_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
lapin = { version = "2.0", features = ["native-tls"] }
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
chrono = "0.4"
futures-lite = "1.12.0"
